In [1]:
from utils.util import *
import geopandas as gpd
from shapely.geometry import shape
import folium
import os
import sys
import time
import pandas as pd
datasets = ['landsat_ot_c2_l2', 'srtm_v3', 'ccdc_v1_3'] 
i = 0
'''['nlcd_collection_lndcov']'''
bandNames = {'B2', 'B3', 'B4', 'B5', 'B6', 'ST_B10'}
years = [2014]
includeMetadata = True

Directory './Unprocessed' already exists.
Directory './Data' already exists.
Directory './RawClippedRasters' already exists.
Directory './Data/LST' already exists.
Directory './Data/NDVI' already exists.
Directory './Data/NDWI' already exists.
Directory './Data/Land_Cover' already exists.
Directory './Data/Albedo' already exists.
Directory './Data/DEM' already exists.
Directory './RawClippedRasters/LST' already exists.
Directory './RawClippedRasters/NDVI' already exists.
Directory './RawClippedRasters/NDWI' already exists.
Directory './RawClippedRasters/Land_Cover' already exists.
Directory './RawClippedRasters/Albedo' already exists.
Directory './RawClippedRasters/DEM' already exists.
Logging in...


Login Successful, API Key Received!

In [2]:
# Cell 2: Load shape file
shapefile_folder = "./Data/area_shp/"
shapefile = "Polygon_San_Antonio_TX.shp"
city = shapefile.replace('Polygon_', '').replace('.shp', '')
aoi_geodf = gpd.read_file(shapefile_folder + shapefile)
aoi_geodf = aoi_geodf.to_crs("EPSG:4326")
if aoi_geodf.empty:
    sys.exit("Error: Shapefile contains no data.")
print("Shapefile loaded successfully.")

Shapefile loaded successfully.

In [3]:
search_payload = createSceneSearchPayload(datasets[i], aoi_geodf, years[0], 20)
scenes = sendRequest(serviceUrl + "scene-search", search_payload, apiKey)
pd.json_normalize(scenes['results'])

,browse,cloudCover,entityId,displayId,orderingId,metadata,hasCustomizedMetadata,publishDate,options.bulk,options.download,...,options.secondary,selected.bulk,selected.compare,selected.order,spatialBounds.type,spatialBounds.coordinates,spatialCoverage.type,spatialCoverage.coordinates,temporalCoverage.endDate,temporalCoverage.startDate
0,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",0,LC80280392014045LGN01,LC08_L2SP_028039_20140214_20200911_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-100.5894, 29.24562], [-100.5894, 31.3535],...",Polygon,"[[[-100.5894, 29.62679], [-98.676, 29.24562], ...",2014-02-14 00:00:00,2014-02-14 00:00:00
1,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",0,LC80280402014045LGN01,LC08_L2SP_028040_20140214_20200911_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-100.94378, 27.80989], [-100.94378, 29.9164...",Polygon,"[[[-100.94378, 28.18863], [-99.0564, 27.80989]...",2014-02-14 00:00:00,2014-02-14 00:00:00
2,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",0,LC80280392014029LGN01,LC08_L2SP_028039_20140129_20200912_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-100.60139, 29.24553], [-100.60139, 31.3534...",Polygon,"[[[-100.60139, 29.62698], [-98.68718, 29.24553...",2014-01-29 00:00:00,2014-01-29 00:00:00
3,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",6,LC80280402014029LGN01,LC08_L2SP_028040_20140129_20200912_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-100.95596, 27.80941], [-100.95596, 29.9159...",Polygon,"[[[-100.95596, 28.18843], [-99.06781, 27.80941...",2014-01-29 00:00:00,2014-01-29 00:00:00
4,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",3,LC80270392014022LGN01,LC08_L2SP_027039_20140122_20200912_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-99.05012, 29.24551], [-99.05012, 31.35347]...",Polygon,"[[[-99.05012, 29.62718], [-97.13482, 29.24551]...",2014-01-22 00:00:00,2014-01-22 00:00:00
5,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",3,LC80270402014022LGN01,LC08_L2SP_027040_20140122_20200912_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-99.40472, 27.8095], [-99.40472, 29.91606],...",Polygon,"[[[-99.40472, 28.18872], [-97.51543, 27.8095],...",2014-01-22 00:00:00,2014-01-22 00:00:00
6,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",0,LC80280392014013LGN01,LC08_L2SP_028039_20140113_20200912_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-100.5826, 29.2458], [-100.5826, 31.35374],...",Polygon,"[[[-100.5826, 29.62753], [-98.66753, 29.2458],...",2014-01-13 00:00:00,2014-01-13 00:00:00
7,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",0,LC80280402014013LGN01,LC08_L2SP_028040_20140113_20200912_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-100.93734, 27.80966], [-100.93734, 29.9161...",Polygon,"[[[-100.93734, 28.18894], [-99.04834, 27.80966...",2014-01-13 00:00:00,2014-01-13 00:00:00

In [4]:
# Cell 7: Collect Entity IDs
entityIds = [result['entityId'] for result in scenes['results'] if result['options']['bulk']]

In [5]:
# Cell 8: Prepare Scene List for Download
listId = f"temp_{datasets[i]}_list"
scn_list_add_payload = {
    "listId": listId,
    'idField': 'entityId',
    "entityIds": entityIds,
    "datasetName": datasets[i]
}
sendRequest(serviceUrl + "scene-list-add", scn_list_add_payload, apiKey)

36

In [6]:
# Cell 9: Prepare Download Options
download_opt_payload = {
    "listId": listId,
    "datasetName": datasets[i],
}
products = sendRequest(serviceUrl + "download-options", download_opt_payload, apiKey)
pd.json_normalize(products)

,id,downloadName,displayId,entityId,datasetId,available,filesize,productName,productCode,bulkAvailable,downloadSystem,secondaryDownloads,fileGroups
0,5e83d14fec7cae84,None,LC08_L2SP_027039_20140122_20200912_02_T1,LC80270392014022LGN01,5e83d14f2fc39685,True,956546961,Landsat Collection 2 Level-2 Product Bundle,D694,True,ls_zip,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
1,6448198cc7b442a4,C2L2 Tile Product Files,LC08_L2SP_027039_20140122_20200912_02_T1,LC80270392014022LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D693,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
2,6448198c62023764,C2L2 Tile Product Files,LC08_L2SP_027039_20140122_20200912_02_T1,LC80270392014022LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D691,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
3,632210d4770592cf,None,LC08_L2SP_027039_20140122_20200912_02_T1,LC80270392014022LGN01,5e83d14f2fc39685,False,956546961,Landsat Collection 2 Level-2 Product Bundle,D806,False,dds_ms,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
4,5e83d14fec7cae84,None,LC08_L2SP_027039_20140311_20200911_02_T1,LC80270392014070LGN01,5e83d14f2fc39685,True,1037754774,Landsat Collection 2 Level-2 Product Bundle,D694,True,ls_zip,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
139,632210d4770592cf,None,LC08_L2SP_028040_20140910_20200910_02_T1,LC80280402014253LGN01,5e83d14f2fc39685,False,992816274,Landsat Collection 2 Level-2 Product Bundle,D806,False,dds_ms,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
140,5e83d14fec7cae84,None,LC08_L2SP_028040_20141129_20200910_02_T1,LC80280402014333LGN01,5e83d14f2fc39685,True,979590335,Landsat Collection 2 Level-2 Product Bundle,D694,True,ls_zip,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
141,6448198cc7b442a4,C2L2 Tile Product Files,LC08_L2SP_028040_20141129_20200910_02_T1,LC80280402014333LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D693,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
142,6448198c62023764,C2L2 Tile Product Files,LC08_L2SP_028040_20141129_20200910_02_T1,LC80280402014333LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D691,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
143,632210d4770592cf,None,LC08_L2SP_028040_20141129_20200910_02_T1,LC80280402014333LGN01,5e83d14f2fc39685,False,979590335,Landsat Collection 2 Level-2 Product Bundle,D806,False,dds_ms,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None

In [7]:
# Cell 10: Collect Files to Download
downloads = []
if 'landsat_ot_c2_l2' in datasets[i]:
    for product in products:
        if product["secondaryDownloads"]:
            for secDownload in product["secondaryDownloads"]:
                if secDownload["bulkAvailable"] and any(band in secDownload['displayId'] for band in bandNames):
                    downloads.append({"entityId": secDownload["entityId"], "productId": secDownload["id"]})
                if includeMetadata and secDownload['displayId'].endswith('_MTL.txt'):
                    downloads.append({"entityId": secDownload["entityId"], "productId": secDownload["id"]})
elif 'srtm_v3' in datasets[i]:
    for product in products:
        if product["bulkAvailable"] and product["entityId"] and product["id"]:
            downloads.append({"entityId": product["entityId"], "productId": product["id"]})
elif 'ccdc_v1_3' in datasets[i]:
    for product in products:
        if product["bulkAvailable"] and product["entityId"] and product["id"]:
            downloads.append({"entityId": product["entityId"], "productId": product["id"]})

In [8]:
# Cell 11: Submit Download Request
download_req_payload = {
    "downloads": downloads,
    "label": listId
}
download_request_results = sendRequest(serviceUrl + "download-request", download_req_payload, apiKey)

In [9]:
print(download_request_results)

{'availableDownloads': [{'downloadId': 715503180, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140318_20200911_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140318_20200911_02_T1/LC08_L2SP_028040_20140318_20200911_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4MCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MTktMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDAzMThfMjAyMDA5MTFfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJGE1UnNzUGNEZGN0S1ZFMWszb0RJNmdcL3ZLdVM3RG96YUNPZk5hYjVrTktBIn0='}, {'downloadId': 715503182, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140318_20200911_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140318_20200911_02_T1/LC08_L2SP_028040_20140318_20200911_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4MiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MTktMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDAzMThfMjAyMDA5MTFfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCQxbXp2b2ROUDVhWE4uVDlwTDZCaVdvWmh0Rkh6QTdhZ2NURkpnQzFIS0EuIn0='}, {'downloadId': 715503183, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140505_20200911_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140505_20200911_02_T1/LC08_L2SP_028040_20140505_20200911_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4MywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MTktMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA1MDVfMjAyMDA5MTFfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCRpQTQ4ZHBUU3BMSnY2STVMb0JSNjVodEFNN2dLekU1Z0c3RnowOXhINHdCIn0='}, {'downloadId': 715503184, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140505_20200911_02_T1/LC08_L2SP_028040_20140505_20200911_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4NCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA1MDVfMjAyMDA5MTFfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJC5uUVl0NzJ4WEdIWWVzTVh6OTJ3T2dKZk11SndSSVdsQUtlRGl2azZZUzcifQ=='}, {'downloadId': 715503185, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140505_20200911_02_T1/LC08_L2SP_028040_20140505_20200911_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4NSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA1MDVfMjAyMDA5MTFfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJFlZRjJxdFwvV3AxdGlnLk41TjFxRENobDBhRlpmQUIxbklyenloeDRHNVc1In0='}, {'downloadId': 715503186, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140505_20200911_02_T1/LC08_L2SP_028040_20140505_20200911_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4NiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA1MDVfMjAyMDA5MTFfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJGpFTkJIZWdqV2IxbUtNUHV3cHVTRmhhXC9kRzkuT29MVlpPNGlLY1RkMTc0In0='}, {'downloadId': 715503187, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140505_20200911_02_T1/LC08_L2SP_028040_20140505_20200911_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4NywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA1MDVfMjAyMDA5MTFfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJE5nZ2k0SkQwSUlBTDk0dnpmV3ZIMUlpeFhVckYyNFZma3pKbzNwSVI1RUMifQ=='}, {'downloadId': 715503188, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140505_20200911_02_T1/LC08_L2SP_028040_20140505_20200911_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4OCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA1MDVfMjAyMDA5MTFfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJHVIWWxOXC80a0lKRUNwQ0FacEJOSWpvTU9ZYTNCNlAuT0FJRVljSGk5XC9nMCJ9'}, {'downloadId': 715503189, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140505_20200911_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140505_20200911_02_T1/LC08_L2SP_028040_20140505_20200911_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE4OSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA1MDVfMjAyMDA5MTFfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCRUZHJmUG12WUo4NFZPcTdULkcuV2t1YzBmdk9MQlFneXEubFFaRWhKVXBCIn0='}, {'downloadId': 715503190, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140708_20200911_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140708_20200911_02_T1/LC08_L2SP_028040_20140708_20200911_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5MCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA3MDhfMjAyMDA5MTFfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCQ4UlA2bXh5ZHE3VTZSbGR0QWxhcDBSSllcLzM3RTJRYi5ha01hYWlmWWVYRCJ9'}, {'downloadId': 715503191, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140708_20200911_02_T1/LC08_L2SP_028040_20140708_20200911_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5MSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA3MDhfMjAyMDA5MTFfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJFRZUFpVT2F6bElJNHVIa0JxN3VaVTY2WFlRT01FRmU0eHAzRHJSclJkNzQifQ=='}, {'downloadId': 715503192, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140708_20200911_02_T1/LC08_L2SP_028040_20140708_20200911_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5MiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA3MDhfMjAyMDA5MTFfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJEw1dnIxWkpPVFVOVTBGVXRhN3RPXC8xeUJHc2I4YklTaHR5bkcuczVzSVhBIn0='}, {'downloadId': 715503193, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140708_20200911_02_T1/LC08_L2SP_028040_20140708_20200911_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5MywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA3MDhfMjAyMDA5MTFfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJDZJV2t2MVROLlNjT2dxSVROVVlpazYyT0hoZlp5UTZONzhVcFdtZ2szcDYifQ=='}, {'downloadId': 715503194, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140708_20200911_02_T1/LC08_L2SP_028040_20140708_20200911_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5NCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA3MDhfMjAyMDA5MTFfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJGFvLkVWaXUuXC9wOWZKdjJqQUZHZ0VBNS5OOWdLdFlrbHI5WnZSY1Ztc3I3In0='}, {'downloadId': 715503195, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140708_20200911_02_T1/LC08_L2SP_028040_20140708_20200911_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5NSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA3MDhfMjAyMDA5MTFfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJEZFcXgxOW9mWmdsWjVGWHowQVN4RXNXeUx0UDZRY3NLSXp6YjIxbTlyZzUifQ=='}, {'downloadId': 715503196, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140708_20200911_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140708_20200911_02_T1/LC08_L2SP_028040_20140708_20200911_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5NiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA3MDhfMjAyMDA5MTFfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCQxMC50RkM4WGhjaHRweUJja0R1dkMyMVZlS3lheExcL0kwQnJ4YWMyREdZLiJ9'}, {'downloadId': 715503197, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140825_20200911_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140825_20200911_02_T1/LC08_L2SP_028040_20140825_20200911_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5NywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA4MjVfMjAyMDA5MTFfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCRWcE5zeFQ5amZrVkhibENzS3h3bUo1OGJXRnlpNXdGa0ZsUFM4YVwvcTRuOSJ9'}, {'downloadId': 715503198, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140825_20200911_02_T1/LC08_L2SP_028040_20140825_20200911_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5OCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA4MjVfMjAyMDA5MTFfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJGZILlwvTXhnZy5HWlQ4QTJ0c0JSZzJYSVNDRjFxeFp6T25KbmhGNklHMFBBIn0='}, {'downloadId': 715503199, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140825_20200911_02_T1/LC08_L2SP_028040_20140825_20200911_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzE5OSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA4MjVfMjAyMDA5MTFfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJFcuZ09qVFI4elMyWVRET2ZzOU9ObFFGNjlUWjBWaWo3MmRDcno4ZU5XdkQifQ=='}, {'downloadId': 715503200, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140825_20200911_02_T1/LC08_L2SP_028040_20140825_20200911_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwMCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA4MjVfMjAyMDA5MTFfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJDlSN21RUkZJUmZcLzVlSFdcLzlFZmhpdmZCT2g0RGdUM0ZyM1UxSHc2SnduNiJ9'}, {'downloadId': 715503201, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140825_20200911_02_T1/LC08_L2SP_028040_20140825_20200911_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwMSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjAtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA4MjVfMjAyMDA5MTFfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJEZvOTBWM004R2lITUllblc1QzNVdDR2TTV3d1VPOTNIVUpOS3lMUGdcLzBCIn0='}, {'downloadId': 715503202, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140825_20200911_02_T1/LC08_L2SP_028040_20140825_20200911_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwMiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA4MjVfMjAyMDA5MTFfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJERsZWNjVHQ2TmYxbVc5N1NqbHRxaS5SNXFHRS5ma25ReDBFa1J0cHJnLjkifQ=='}, {'downloadId': 715503203, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140825_20200911_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140825_20200911_02_T1/LC08_L2SP_028040_20140825_20200911_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwMywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA4MjVfMjAyMDA5MTFfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCRFdVBKVVFVZkVBSks3eG9GU2s1LkpGU1haWkpUUEF6Lm4xVWh2amFvZkRcLyJ9'}, {'downloadId': 715503204, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140910_20200910_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140910_20200910_02_T1/LC08_L2SP_028040_20140910_20200910_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwNCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA5MTBfMjAyMDA5MTBfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCR6azgwc3lFLnllN1d0YWhMRVR6ZWhPdVgyamlBa1J2ZEM3c2VHbWpUdTIxIn0='}, {'downloadId': 715503205, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140910_20200910_02_T1/LC08_L2SP_028040_20140910_20200910_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwNSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA5MTBfMjAyMDA5MTBfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJHJIV2dkblZ6U3JrRUxwUldMR2IyMjdmR0tjSndPY1ZnTUtraXpjSm1IeFwvIn0='}, {'downloadId': 715503206, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140910_20200910_02_T1/LC08_L2SP_028040_20140910_20200910_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwNiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA5MTBfMjAyMDA5MTBfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJHBSaEV1QzdiT0FROHl4aDRGb0gxMENIQk5FQVwvbUlEVEZFRGN4VVlOTTg3In0='}, {'downloadId': 715503207, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140910_20200910_02_T1/LC08_L2SP_028040_20140910_20200910_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwNywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA5MTBfMjAyMDA5MTBfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJEE5VkU2bzhjQnl2ejBxcXdiTE5CcDIzdDZmaGZGdS51UEhZQWNxQjliNzQifQ=='}, {'downloadId': 715503208, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140910_20200910_02_T1/LC08_L2SP_028040_20140910_20200910_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwOCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA5MTBfMjAyMDA5MTBfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJDUxWjVTTGJaVnhPN2ZjXC81M0txdFRoYVNvbU1LXC92LnhUSHhzYlpBbVpuQSJ9'}, {'downloadId': 715503209, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140910_20200910_02_T1/LC08_L2SP_028040_20140910_20200910_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIwOSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA5MTBfMjAyMDA5MTBfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJDBtSkZcL3BHUnZKSXhPNElkSVwvTmxkbmIxN2x3bHdLSmtSVkhjaHBGcmphNSJ9'}, {'downloadId': 715503210, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20140910_20200910_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20140910_20200910_02_T1/LC08_L2SP_028040_20140910_20200910_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIxMCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDA5MTBfMjAyMDA5MTBfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCRJemN5N0lwc1ppWVMwYWNZU3VaelwvU1ljUGZ2QUh0RzZwXC9kS3FFcnhtdDcifQ=='}, {'downloadId': 715503211, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_028040_20141129_20200910_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20141129_20200910_02_T1/LC08_L2SP_028040_20141129_20200910_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIxMSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMjgwNDBfMjAxNDExMjlfMjAyMDA5MTBfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCRrQ1kyOWJnRkllTDZ4bTU2QjFvWkFlblVxMjl6WVk2cGlrV1FwbjF1Sk83In0='}, {'downloadId': 715503212, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_028040_20141129_20200910_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2014/028/040/LC08_L2SP_028040_20141129_20200910_02_T1/LC08_L2SP_028040_20141129_20200910_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTUwMzIxMiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTA6Mzg6MjEtMDY6MDAiLCJpZCI6Ik

In [ ]:
# Cell 12: Download Files
if datasets[i] == 'landsat_ot_c2_l2':
    results = download_request_results['availableDownloads']
    for result in results:
        runDownload(threads, result['url'])
elif datasets[i] == 'srtm_v3':
    result = download_request_results['preparingDownloads'][2]
    runDownload(threads, result['url'])
else:
    result = download_request_results['preparingDownloads'][0]
    runDownload(threads, result['url'])
for _, t in enumerate(threads):
    t.join()
for file in os.listdir('./Unprocessed'):
    if file.endswith('.tar'):
        try: 
            extract_specific_files('./Unprocessed/' + file, './Unprocessed')
        except:
            print(f'Error: Could not extract file {file}')

    Downloading: LC08_L2SP_028040_20140318_20200911_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_028040_20140505_20200911_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_028040_20140318_20200911_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_028040_20140505_20200911_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_028040_20140505_20200911_02_T1_MTL.txt...
    Downloading: LC08_L2SP_028040_20140505_20200911_02_T1_SR_B4.TIF...
    Downloading: LC08_L2SP_028040_20140505_20200911_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_028040_20140505_20200911_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_028040_20140505_20200911_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_028040_20140708_20200911_02_T1_MTL.txt...
    Downloading: LC08_L2SP_028040_20140708_20200911_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_028040_20140708_20200911_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_028040_20140708_20200911_02_T1_SR_B4.TIF...
    Downloading: LC08_L2SP_028040_20140708_20200911_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_028040_20140708_20200911_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_028040_20140708_20200911_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_028040_20140825_20200911_02_T1_MTL.txt...
    Downloading: LC08_L2SP_028040_20140825_20200911_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_028040_20140825_20200911_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_028040_20140825_20200911_02_T1_SR_B4.TIF...
    Downloading: LC08_L2SP_028040_20140825_20200911_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_028040_20140825_20200911_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_028040_20140825_20200911_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_028040_20140910_20200910_02_T1_MTL.txt...
    Downloading: LC08_L2SP_028040_20140910_20200910_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_028040_20140910_20200910_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_028040_20140910_20200910_02_T1_SR_B4.TIF...
    Downloading: LC08_L2SP_028040_20140910_20200910_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_028040_20140910_20200910_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_028040_20140910_20200910_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_028040_20141129_20200910_02_T1_MTL.txt...
    Downloading: LC08_L2SP_028040_20141129_20200910_02_T1_SR_B2.TIF...

In [ ]:
# Cell 13: Clean Up
remove_scnlst_payload = {"listId": listId}
sendRequest(serviceUrl + "scene-list-remove", remove_scnlst_payload, apiKey)

In [9]:
# Cell 15: Verify Downloads
import rasterio
from shapely.geometry import box

usableTIFFs = []
print(os.listdir(unprocessed_dir))
# Ensure the shapefile matches the TIF CRS
for tif_file in os.listdir(unprocessed_dir):
    if tif_file.endswith(".TIF") or tif_file.endswith(".tif"):
        tif_path = unprocessed_dir + '/' + tif_file
        with rasterio.open(tif_path) as src:
            # Reproject shapefile to match TIF file CRS
            aoi_geodf_proj = aoi_geodf.to_crs(src.crs)
            tif_bounds = box(*src.bounds)
            
            # Check containment
            for idx, geom in enumerate(aoi_geodf_proj.geometry):
                if tif_bounds.contains(geom):
                    usableTIFFs.append(tif_file)
                    print(f"Polygon {city} is fully inside {tif_file}")
                else:
                    print(f"Polygon {city} is NOT fully inside {tif_file}")
print(usableTIFFs)

['LC08_L2SP_028040_20140318_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140318_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_MTL.txt', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B4.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B5.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_MTL.txt', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B4.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B5.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_MTL.txt', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B4.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B5.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140910_20200910_02_T1_MTL.txt', 'LC08_L2SP_028040_20140910_20200910_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140910_20200910_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140910_20200910_02_T1_SR_B5.TIF', 'LC08_L2SP_028040_20141129_20200910_02_T1_MTL.txt']
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140318_20200911_02_T1_SR_B6.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140318_20200911_02_T1_ST_B10.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140505_20200911_02_T1_SR_B2.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140505_20200911_02_T1_SR_B3.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140505_20200911_02_T1_SR_B4.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140505_20200911_02_T1_SR_B5.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140505_20200911_02_T1_SR_B6.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140505_20200911_02_T1_ST_B10.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140708_20200911_02_T1_SR_B2.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140708_20200911_02_T1_SR_B3.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140708_20200911_02_T1_SR_B4.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140708_20200911_02_T1_SR_B5.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140708_20200911_02_T1_SR_B6.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140708_20200911_02_T1_ST_B10.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140825_20200911_02_T1_SR_B2.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140825_20200911_02_T1_SR_B3.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140825_20200911_02_T1_SR_B4.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140825_20200911_02_T1_SR_B5.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140825_20200911_02_T1_SR_B6.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140825_20200911_02_T1_ST_B10.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140910_20200910_02_T1_SR_B2.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140910_20200910_02_T1_SR_B3.TIF
Polygon San_Antonio_TX is fully inside LC08_L2SP_028040_20140910_20200910_02_T1_SR_B5.TIF
['LC08_L2SP_028040_20140318_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140318_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B4.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B5.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140505_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B4.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B5.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140708_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B4.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B5.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_SR_B6.TIF', 'LC08_L2SP_028040_20140825_20200911_02_T1_ST_B10.TIF', 'LC08_L2SP_028040_20140910_20200910_02_T1_SR_B2.TIF', 'LC08_L2SP_028040_20140910_20200910_02_T1_SR_B3.TIF', 'LC08_L2SP_028040_20140910_20200910_02_T1_SR_B5.TIF']

In [10]:
goodCoordinates = clipUnprocessedRasters(usableTIFFs, aoi_geodf_proj)

Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140318_20200911_02_T1_SR_B6.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140318_20200911_02_T1_ST_B10.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B2.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B3.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B4.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B5.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140505_20200911_02_T1_SR_B6.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140505_20200911_02_T1_ST_B10.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B2.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B3.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B4.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B5.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140708_20200911_02_T1_SR_B6.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140708_20200911_02_T1_ST_B10.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B2.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B3.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B4.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B5.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140825_20200911_02_T1_SR_B6.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140825_20200911_02_T1_ST_B10.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B2.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B3.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_028040_20140910_20200910_02_T1_SR_B5.TIF

In [ ]:
for file in os.listdir(unprocessed_dir):
    if ".txt" in file or "Clipped_" in file:
        if '1arc_v3' in file:
            moveToRaw(file, 'DEM', f'{years[0]}-01-01', city)
            continue
        if 'LCMAP' in file:
            if 'LCPRI' in file:
                moveToRaw(file, 'Land_Cover', f'{years[0]}-01-01', city)
            continue
        date, band, coordinate = getMetaFromLandsatTIRs(file)
        if coordinate not in goodCoordinates:
            continue
        print(date, band)
        if band == 'B10':
            moveToRaw(file, 'LST', date, city)
        if band == 'B2':
            moveToRaw(file, 'Albedo', date, city)
        if band == 'B3':
            moveToRaw(file, 'NDWI', date, city)
        if band == 'B4':
            moveToRaw(file, 'Albedo', date, city)
            moveToRaw(file, 'NDVI', date, city)
        if band == 'B5':
            moveToRaw(file, 'Albedo', date, city)
            moveToRaw(file, 'NDVI', date, city)
            moveToRaw(file, 'NDWI', date, city)
        if band == 'B6':
            moveToRaw(file, 'Albedo', date, city)
        if band == 'MTL':
            moveToRaw(file, 'Albedo', date, city)
            moveToRaw(file, 'LST', date, city)
            moveToRaw(file, 'NDVI', date, city)
            moveToRaw(file, 'NDWI', date, city)

In [ ]:
clear_folder(unprocessed_dir)