In [1]:
from utils.util import *
import geopandas as gpd
from shapely.geometry import shape
import folium
import os
import sys
import time
import pandas as pd
datasets = ['landsat_ot_c2_l2', 'srtm_v3', 'ccdc_v1_3'] 
i = 0
'''['nlcd_collection_lndcov']'''
bandNames = {'B2', 'B3', 'B4', 'B5', 'B6', 'ST_B10'}
years = [2015]
includeMetadata = True

Directory './Unprocessed' already exists.
Directory './Data' already exists.
Directory './RawClippedRasters' already exists.
Directory './Data/LST' already exists.
Directory './Data/NDVI' already exists.
Directory './Data/NDWI' already exists.
Directory './Data/Land_Cover' already exists.
Directory './Data/Albedo' already exists.
Directory './Data/DEM' already exists.
Directory './RawClippedRasters/LST' already exists.
Directory './RawClippedRasters/NDVI' already exists.
Directory './RawClippedRasters/NDWI' already exists.
Directory './RawClippedRasters/Land_Cover' already exists.
Directory './RawClippedRasters/Albedo' already exists.
Directory './RawClippedRasters/DEM' already exists.
Logging in...


Login Successful, API Key Received!

In [2]:
# Cell 2: Load shape file
shapefile_folder = "./Data/area_shp/"
shapefile = "Polygon_Pahrump_NV.shp"
city = shapefile.replace('Polygon_', '').replace('.shp', '')
aoi_geodf = gpd.read_file(shapefile_folder + shapefile)
aoi_geodf = aoi_geodf.to_crs("EPSG:4326")
if aoi_geodf.empty:
    sys.exit("Error: Shapefile contains no data.")
print("Shapefile loaded successfully.")

Shapefile loaded successfully.

In [3]:
search_payload = createSceneSearchPayload(datasets[i], aoi_geodf, years[0], 20)
scenes = sendRequest(serviceUrl + "scene-search", search_payload, apiKey)
pd.json_normalize(scenes['results'])

,browse,cloudCover,entityId,displayId,orderingId,metadata,hasCustomizedMetadata,publishDate,options.bulk,options.download,...,options.secondary,selected.bulk,selected.compare,selected.order,spatialBounds.type,spatialBounds.coordinates,spatialCoverage.type,spatialCoverage.coordinates,temporalCoverage.endDate,temporalCoverage.startDate
0,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",0,LC80400352015052LGN01,LC08_L2SP_040035_20150221_20200909_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-117.63752, 34.97845], [-117.63752, 37.0933...",Polygon,"[[[-117.63752, 35.3716], [-115.60248, 34.97845...",2015-02-21 00:00:00,2015-02-21 00:00:00
1,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",0,LC80390352015045LGN01,LC08_L2SP_039035_20150214_20200910_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-116.07556, 34.97865], [-116.07556, 37.0936...",Polygon,"[[[-116.07556, 35.37186], [-114.04067, 34.9786...",2015-02-14 00:00:00,2015-02-14 00:00:00
2,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",16,LC80400352015036LGN01,LC08_L2SP_040035_20150205_20200909_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-117.63427, 34.9787], [-117.63427, 37.09369...",Polygon,"[[[-117.63427, 35.37195], [-115.59936, 34.9787...",2015-02-05 00:00:00,2015-02-05 00:00:00
3,"[{'id': '5fb4ba12d7ec307f', 'browseRotationEna...",2,LC80390352015013LGN01,LC08_L2SP_039035_20150113_20200910_02_T1,None,"[{'id': '5e83d1508031a4a3', 'fieldName': 'ID',...",None,2022-06-22 18:27:47-05,True,True,...,False,False,False,False,Polygon,"[[[-116.08404, 34.97836], [-116.08404, 37.0934...",Polygon,"[[[-116.08404, 35.37173], [-114.04924, 34.9783...",2015-01-13 00:00:00,2015-01-13 00:00:00

In [4]:
# Cell 7: Collect Entity IDs
entityIds = [result['entityId'] for result in scenes['results'] if result['options']['bulk']]

In [5]:
# Cell 8: Prepare Scene List for Download
listId = f"temp_{datasets[i]}_list"
scn_list_add_payload = {
    "listId": listId,
    'idField': 'entityId',
    "entityIds": entityIds,
    "datasetName": datasets[i]
}
sendRequest(serviceUrl + "scene-list-add", scn_list_add_payload, apiKey)

4

In [6]:
# Cell 9: Prepare Download Options
download_opt_payload = {
    "listId": listId,
    "datasetName": datasets[i],
}
products = sendRequest(serviceUrl + "download-options", download_opt_payload, apiKey)
pd.json_normalize(products)

,id,downloadName,displayId,entityId,datasetId,available,filesize,productName,productCode,bulkAvailable,downloadSystem,secondaryDownloads,fileGroups
0,5e83d14fec7cae84,None,LC08_L2SP_039035_20150113_20200910_02_T1,LC80390352015013LGN01,5e83d14f2fc39685,True,975547025,Landsat Collection 2 Level-2 Product Bundle,D694,True,ls_zip,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
1,6448198cc7b442a4,C2L2 Tile Product Files,LC08_L2SP_039035_20150113_20200910_02_T1,LC80390352015013LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D693,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
2,6448198c62023764,C2L2 Tile Product Files,LC08_L2SP_039035_20150113_20200910_02_T1,LC80390352015013LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D691,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
3,632210d4770592cf,None,LC08_L2SP_039035_20150113_20200910_02_T1,LC80390352015013LGN01,5e83d14f2fc39685,False,975547025,Landsat Collection 2 Level-2 Product Bundle,D806,False,dds_ms,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
4,5e83d14fec7cae84,None,LC08_L2SP_039035_20150214_20200910_02_T1,LC80390352015045LGN01,5e83d14f2fc39685,True,976073199,Landsat Collection 2 Level-2 Product Bundle,D694,True,ls_zip,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
5,6448198cc7b442a4,C2L2 Tile Product Files,LC08_L2SP_039035_20150214_20200910_02_T1,LC80390352015045LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D693,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
6,6448198c62023764,C2L2 Tile Product Files,LC08_L2SP_039035_20150214_20200910_02_T1,LC80390352015045LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D691,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
7,632210d4770592cf,None,LC08_L2SP_039035_20150214_20200910_02_T1,LC80390352015045LGN01,5e83d14f2fc39685,False,976073199,Landsat Collection 2 Level-2 Product Bundle,D806,False,dds_ms,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
8,5e83d14fec7cae84,None,LC08_L2SP_040035_20150205_20200909_02_T1,LC80400352015036LGN01,5e83d14f2fc39685,True,966757933,Landsat Collection 2 Level-2 Product Bundle,D694,True,ls_zip,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
9,6448198cc7b442a4,C2L2 Tile Product Files,LC08_L2SP_040035_20150205_20200909_02_T1,LC80400352015036LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D693,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
10,6448198c62023764,C2L2 Tile Product Files,LC08_L2SP_040035_20150205_20200909_02_T1,LC80400352015036LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D691,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
11,632210d4770592cf,None,LC08_L2SP_040035_20150205_20200909_02_T1,LC80400352015036LGN01,5e83d14f2fc39685,False,966757933,Landsat Collection 2 Level-2 Product Bundle,D806,False,dds_ms,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
12,5e83d14fec7cae84,None,LC08_L2SP_040035_20150221_20200909_02_T1,LC80400352015052LGN01,5e83d14f2fc39685,True,957216528,Landsat Collection 2 Level-2 Product Bundle,D694,True,ls_zip,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
13,6448198cc7b442a4,C2L2 Tile Product Files,LC08_L2SP_040035_20150221_20200909_02_T1,LC80400352015052LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D693,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
14,6448198c62023764,C2L2 Tile Product Files,LC08_L2SP_040035_20150221_20200909_02_T1,LC80400352015052LGN01,5e83d14f2fc39685,True,0,Landsat Collection 2 Level-2 Band File,D691,True,folder,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None
15,632210d4770592cf,None,LC08_L2SP_040035_20150221_20200909_02_T1,LC80400352015052LGN01,5e83d14f2fc39685,False,957216528,Landsat Collection 2 Level-2 Product Bundle,D806,False,dds_ms,"[{'id': '5f85f041a2ea6695', 'downloadName': No...",None

In [7]:
# Cell 10: Collect Files to Download
downloads = []
if 'landsat_ot_c2_l2' in datasets[i]:
    for product in products:
        if product["secondaryDownloads"]:
            for secDownload in product["secondaryDownloads"]:
                if secDownload["bulkAvailable"] and any(band in secDownload['displayId'] for band in bandNames):
                    downloads.append({"entityId": secDownload["entityId"], "productId": secDownload["id"]})
                if includeMetadata and secDownload['displayId'].endswith('_MTL.txt'):
                    downloads.append({"entityId": secDownload["entityId"], "productId": secDownload["id"]})
elif 'srtm_v3' in datasets[i]:
    for product in products:
        if product["bulkAvailable"] and product["entityId"] and product["id"]:
            downloads.append({"entityId": product["entityId"], "productId": product["id"]})
elif 'ccdc_v1_3' in datasets[i]:
    for product in products:
        if product["bulkAvailable"] and product["entityId"] and product["id"]:
            downloads.append({"entityId": product["entityId"], "productId": product["id"]})

In [8]:
# Cell 11: Submit Download Request
download_req_payload = {
    "downloads": downloads,
    "label": listId
}
download_request_results = sendRequest(serviceUrl + "download-request", download_req_payload, apiKey)

In [9]:
print(download_request_results)

{'availableDownloads': [{'downloadId': 715586891, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_039035_20150113_20200910_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150113_20200910_02_T1/LC08_L2SP_039035_20150113_20200910_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5MSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAxMTNfMjAyMDA5MTBfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCRtOXAzS3R4RFJkUzhLbmg5N2JYbEpHTVJuQllZWlp4d0RoR0sxb2JvbEZBIn0='}, {'downloadId': 715586892, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150113_20200910_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150113_20200910_02_T1/LC08_L2SP_039035_20150113_20200910_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5MiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAxMTNfMjAyMDA5MTBfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJFwvZHB1MGdTUHJlOUJFSEZFWlVHMWhuUW1wNDRkN2dnVHpMZXhidHhrNGszIn0='}, {'downloadId': 715586893, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150113_20200910_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150113_20200910_02_T1/LC08_L2SP_039035_20150113_20200910_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5MywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAxMTNfMjAyMDA5MTBfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJGgxM1ZcLzNlWG9ZSTFBaC5mV3ZUcUIxc2w5RHRKVmhCNjIwVEh4U09GLnU1In0='}, {'downloadId': 715586894, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150113_20200910_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150113_20200910_02_T1/LC08_L2SP_039035_20150113_20200910_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5NCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAxMTNfMjAyMDA5MTBfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJC5hTzZET1FxXC8zYzZcL2p0ZjA2VXc4bWE4dFlBYVNtd09VRmN6ZW9NRE1wRCJ9'}, {'downloadId': 715586895, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150113_20200910_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150113_20200910_02_T1/LC08_L2SP_039035_20150113_20200910_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5NSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAxMTNfMjAyMDA5MTBfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJHdNd1Y5T1VscHIzaXJkUVZTd2N3bW1QVDU5UGdQeVdsNENhb0JRb1ZhaVwvIn0='}, {'downloadId': 715586896, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150113_20200910_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150113_20200910_02_T1/LC08_L2SP_039035_20150113_20200910_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5NiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAxMTNfMjAyMDA5MTBfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJFFCZ09kc1dGZThBSEJiTEJIaEZraWV1T2pjYmJENmxYaEsxXC9GR084WEdcLyJ9'}, {'downloadId': 715586897, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_039035_20150113_20200910_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150113_20200910_02_T1/LC08_L2SP_039035_20150113_20200910_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5NywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAxMTNfMjAyMDA5MTBfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCRQM2pxS2FuYi4xVm9OTVhySld1aGtsbW9iXC94NUx1Q1NhbjFuaXdWY0szMSJ9'}, {'downloadId': 715586898, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_039035_20150214_20200910_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150214_20200910_02_T1/LC08_L2SP_039035_20150214_20200910_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5OCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAyMTRfMjAyMDA5MTBfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCR0Q2VRVjJaenNHaUtWUklGczBVTWxzOE0yajBQQVBndVlCbkRYMjVwakkzIn0='}, {'downloadId': 715586899, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150214_20200910_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150214_20200910_02_T1/LC08_L2SP_039035_20150214_20200910_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4Njg5OSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAyMTRfMjAyMDA5MTBfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJGJYYTdqQ2h1eFwvaC5GZnpFLk5JNnl3OTZGZGdmbTRxekk4NW02SU9RR1IuIn0='}, {'downloadId': 715586900, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150214_20200910_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150214_20200910_02_T1/LC08_L2SP_039035_20150214_20200910_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwMCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAyMTRfMjAyMDA5MTBfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJDVSbWtSS1U5ZWZ2VlBWUEkzSVd1dGVSZHVsaU83MGxLOE15NVVFR1dNbEMifQ=='}, {'downloadId': 715586901, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150214_20200910_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150214_20200910_02_T1/LC08_L2SP_039035_20150214_20200910_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwMSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAyMTRfMjAyMDA5MTBfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJDhjR01FUWdRTGphRFg0MmxlMVVZUm1BeVBrdDFPcDFGZ3RqYnlMaXBWMy4ifQ=='}, {'downloadId': 715586902, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150214_20200910_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150214_20200910_02_T1/LC08_L2SP_039035_20150214_20200910_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwMiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAyMTRfMjAyMDA5MTBfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJGV3NnNRZkszNzE4NVFGcFpuMDVyaFM3MjhkSTZNbGg0R1UwNXZYYm5yblwvIn0='}, {'downloadId': 715586903, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_039035_20150214_20200910_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150214_20200910_02_T1/LC08_L2SP_039035_20150214_20200910_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwMywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAyMTRfMjAyMDA5MTBfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJHZybE8zYnEzZVVJZElqTE51V2RzNmF0Ym9RRmJLMWF3V3NIcXJ5V1luNUIifQ=='}, {'downloadId': 715586904, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_039035_20150214_20200910_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/039/035/LC08_L2SP_039035_20150214_20200910_02_T1/LC08_L2SP_039035_20150214_20200910_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwNCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wMzkwMzVfMjAxNTAyMTRfMjAyMDA5MTBfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCRVQ25yNVFpV3d6STFnNFdSeXM5am1yN3pZNzZqS2RLeXN6TU1YQVZHSmlcLyJ9'}, {'downloadId': 715586905, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_040035_20150205_20200909_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150205_20200909_02_T1/LC08_L2SP_040035_20150205_20200909_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwNSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDctMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMDVfMjAyMDA5MDlfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCROQjMxWGR1YmRJSndUSEloQmVtc1V0SXNNcldvaGI1VC5lZ0ZpZHUyV0lcLyJ9'}, {'downloadId': 715586906, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150205_20200909_02_T1/LC08_L2SP_040035_20150205_20200909_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwNiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMDVfMjAyMDA5MDlfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJGtBOU1lZ1ZLNVwvRFk0MDl3b0UzdFBheVRzXC93R1B2UWFsQk1oXC9aRDEwajMifQ=='}, {'downloadId': 715586907, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150205_20200909_02_T1/LC08_L2SP_040035_20150205_20200909_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwNywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMDVfMjAyMDA5MDlfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJEtEZXpmTTdTdGZqWW01aC5NQnYxdUl3U2I5dDhsN2JOV3RYa2pncm9kdDAifQ=='}, {'downloadId': 715586908, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150205_20200909_02_T1/LC08_L2SP_040035_20150205_20200909_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwOCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMDVfMjAyMDA5MDlfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJEhcLzY4cGh0b0QweXBcLzdmMzdpQkc4UEx0NjV3NHU3YzRKTG1KS2xEem9VOCJ9'}, {'downloadId': 715586909, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150205_20200909_02_T1/LC08_L2SP_040035_20150205_20200909_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkwOSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMDVfMjAyMDA5MDlfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJGQ2ek44T0wxbExsQ1R2MENkM09xUngzRFp0WXJ3WXRiQ0FQaEJPRDJSSDIifQ=='}, {'downloadId': 715586910, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150205_20200909_02_T1/LC08_L2SP_040035_20150205_20200909_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxMCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMDVfMjAyMDA5MDlfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJDBuczc4NUQ5YUg0OFUwdmZcL1FmdjhWcmttaVEzWjBUNVRKNXliclh6WGJBIn0='}, {'downloadId': 715586911, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_040035_20150205_20200909_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150205_20200909_02_T1/LC08_L2SP_040035_20150205_20200909_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxMSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMDVfMjAyMDA5MDlfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCR2M1lMaVwvWkV5LlJNVUxldnRGMG5EbTdnMjhPWTZmazJqSVdTRWdyVXc3NiJ9'}, {'downloadId': 715586912, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_040035_20150221_20200909_02_T1_MTL_TXT', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150221_20200909_02_T1/LC08_L2SP_040035_20150221_20200909_02_T1_MTL.txt?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxMiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMjFfMjAyMDA5MDlfMDJfVDFfTVRMLnR4dCIsInNpZ25hdHVyZSI6IiQ1JCRPM1U3TTkxb0xMZ2NxNVZIeWFDVzFCeS5zRVhBNnp0c1pEOWpcL2JzT3JqQyJ9'}, {'downloadId': 715586913, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150221_20200909_02_T1_SR_B2_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150221_20200909_02_T1/LC08_L2SP_040035_20150221_20200909_02_T1_SR_B2.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxMywiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMjFfMjAyMDA5MDlfMDJfVDFfU1JfQjIuVElGIiwic2lnbmF0dXJlIjoiJDUkJDNtU1FRa3diSW50ZE9LaHo4eUduQTBYNDRUbWo5dk1oV2lDVGlOMHpMeDUifQ=='}, {'downloadId': 715586914, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150221_20200909_02_T1_SR_B3_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150221_20200909_02_T1/LC08_L2SP_040035_20150221_20200909_02_T1_SR_B3.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxNCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMjFfMjAyMDA5MDlfMDJfVDFfU1JfQjMuVElGIiwic2lnbmF0dXJlIjoiJDUkJFwvMTZZN1JhS0xcL09LVkEuSlI1eTZDSmhJV0xHNEpIM1JvbVIubkozeHR1MSJ9'}, {'downloadId': 715586915, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150221_20200909_02_T1_SR_B4_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150221_20200909_02_T1/LC08_L2SP_040035_20150221_20200909_02_T1_SR_B4.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxNSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMjFfMjAyMDA5MDlfMDJfVDFfU1JfQjQuVElGIiwic2lnbmF0dXJlIjoiJDUkJC5Cd1wvNEk0ck1BaWQycUNwZko4bEcwNTVkQjFtekNHVDRjeEZyZ0FqNUEwIn0='}, {'downloadId': 715586916, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150221_20200909_02_T1_SR_B5_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150221_20200909_02_T1/LC08_L2SP_040035_20150221_20200909_02_T1_SR_B5.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxNiwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMjFfMjAyMDA5MDlfMDJfVDFfU1JfQjUuVElGIiwic2lnbmF0dXJlIjoiJDUkJHJmZDEzZDNHRzVRRE9ZREozOFI1YXZYNy5EMUhhVTdrQkk0U1lwVzYxMjgifQ=='}, {'downloadId': 715586918, 'eulaCode': None, 'entityId': 'L2SR_LC08_L2SP_040035_20150221_20200909_02_T1_SR_B6_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150221_20200909_02_T1/LC08_L2SP_040035_20150221_20200909_02_T1_SR_B6.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxOCwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMjFfMjAyMDA5MDlfMDJfVDFfU1JfQjYuVElGIiwic2lnbmF0dXJlIjoiJDUkJGFWeU5TWlI1akQ3VWJrR2gzaFwvNjZBSmJrQWk2NUFYXC9DN2hkUG9Xay5TNiJ9'}, {'downloadId': 715586919, 'eulaCode': None, 'entityId': 'L2ST_LC08_L2SP_040035_20150221_20200909_02_T1_ST_B10_TIF', 'url': 'https://landsatlook.usgs.gov/data/collection02/level-2/standard/oli-tirs/2015/040/035/LC08_L2SP_040035_20150221_20200909_02_T1/LC08_L2SP_040035_20150221_20200909_02_T1_ST_B10.TIF?requestSignature=eyJkb3dubG9hZEFwcCI6Ik0yTSIsImNvbnRhY3RJZCI6MjczNjI1NzcsImRvd25sb2FkSWQiOjcxNTU4NjkxOSwiZGF0ZUdlbmVyYXRlZCI6IjIwMjQtMTItMjFUMTM6NTU6MDgtMDY6MDAiLCJpZCI6IkxDMDhfTDJTUF8wNDAwMzVfMjAxNTAyMjFfMjAyMDA5MDlfMDJfVDFfU1RfQjEwLlRJRiIsInNpZ25hdHVyZSI6IiQ1JCQwRDFLXC9kbUJWdkIwbmRDMnJVcGFtYk1iXC9KanM5WG5RUnh0UndRNkc2cDUifQ=='}], 'duplicateProducts': [], 'preparingDownloads': [], 'failed': [], 'newRecords': {'715586891': 'temp_landsat_ot_c2_l2_list', '715586892': 'temp_landsat_ot_c2_l2_list', '715586893': 'temp_landsat_ot_c2_l2_list', '715586894': 'temp_landsat_ot_c2_l2_list', '715586895': 'temp_landsat_ot_c2_l2_list', '715586896': 'temp_landsat_ot_c2_l2_list', '715586897': 'temp_landsat_ot_c2_l2_list', '715586898': 'temp_landsat_ot_c2_l2_list', '715586899': 'temp_landsat_ot_c2_l2_list', '715586900': 'temp_landsat_ot_c2_l2_list', '715586901': 'temp_landsat_ot_c2_l2_list', '715586902': 'temp_landsat_ot_c2_l2_list', '715586903': 'temp_landsat_ot_c2_l2_list', '715586904': 'temp_landsat_ot_c2_l2_list', '715586905': 'temp_landsat_ot_c2_l2_list', '715586906': 'temp_landsat_ot_c2_l2_list', '715586907': 'temp_landsat_ot_c2_l2_list', '715586908': 'temp_landsat_ot_c2_l2_list', '715586909': 'temp_landsat_ot_c2_l2_list', '715586910': 'temp_landsat_ot_c2_l2_list', '715586911': 'temp_landsat_ot_c2_l2_list', '715586912': 'temp_landsat_ot_c2_l2_list', '715586913': 'temp_landsat_ot_c2_l2_list', '715586914': 'temp_landsat_ot_c2_l2_list', '715586915': 'temp_landsat_ot_c2_l2_list', '715586916': 'temp_landsat_ot_c2_l2_list', '715586918': 'temp_landsat_ot_c2_l2_list', '715586919': 'temp_landsat_ot_c2_l2_list'}, 'remainingLimits': [{'limitType': 'user', 'username': 'Jesus.Guerrero', 'recentDownloadCount': 14972, 'pendingDownloadCount': 20000, 'unattemptedDownloadCount': 19988}, {'limitType': 'ip', 'ipAddress': '72.181.123.208', 'recentDownloadCount': 14972, 'pendingDownloadCount': 20000, 'unattemptedDownloadCount': 19988}], 'numInvalidScenes': 84}

In [10]:
# Cell 12: Download Files
if datasets[i] == 'landsat_ot_c2_l2':
    results = download_request_results['availableDownloads']
    for result in results:
        runDownload(threads, result['url'])
elif datasets[i] == 'srtm_v3':
    result = download_request_results['preparingDownloads'][2]
    runDownload(threads, result['url'])
else:
    result = download_request_results['preparingDownloads'][0]
    runDownload(threads, result['url'])
for _, t in enumerate(threads):
    t.join()
for file in os.listdir('./Unprocessed'):
    if file.endswith('.tar'):
        try: 
            extract_specific_files('./Unprocessed/' + file, './Unprocessed')
        except:
            print(f'Error: Could not extract file {file}')

    Downloading: LC08_L2SP_039035_20150113_20200910_02_T1_MTL.txt...
    Downloading: LC08_L2SP_039035_20150113_20200910_02_T1_SR_B4.TIF...
    Downloading: LC08_L2SP_039035_20150113_20200910_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_039035_20150113_20200910_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_039035_20150113_20200910_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_039035_20150113_20200910_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_039035_20150214_20200910_02_T1_MTL.txt...
    Downloading: LC08_L2SP_039035_20150113_20200910_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_039035_20150214_20200910_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_039035_20150214_20200910_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_039035_20150214_20200910_02_T1_SR_B4.TIF...
    Downloading: LC08_L2SP_039035_20150214_20200910_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_039035_20150214_20200910_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_039035_20150214_20200910_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_040035_20150205_20200909_02_T1_MTL.txt...
    Downloading: LC08_L2SP_040035_20150205_20200909_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_040035_20150205_20200909_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_040035_20150205_20200909_02_T1_SR_B4.TIF...
    Downloading: LC08_L2SP_040035_20150205_20200909_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_040035_20150205_20200909_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_040035_20150205_20200909_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_040035_20150221_20200909_02_T1_SR_B2.TIF...
    Downloading: LC08_L2SP_040035_20150221_20200909_02_T1_MTL.txt...
    Downloading: LC08_L2SP_040035_20150221_20200909_02_T1_SR_B3.TIF...
    Downloading: LC08_L2SP_040035_20150221_20200909_02_T1_SR_B6.TIF...
    Downloading: LC08_L2SP_040035_20150221_20200909_02_T1_ST_B10.TIF...
    Downloading: LC08_L2SP_040035_20150221_20200909_02_T1_SR_B5.TIF...
    Downloading: LC08_L2SP_040035_20150221_20200909_02_T1_SR_B4.TIF...

In [11]:
# Cell 13: Clean Up
remove_scnlst_payload = {"listId": listId}
sendRequest(serviceUrl + "scene-list-remove", remove_scnlst_payload, apiKey)

In [12]:
# Cell 15: Verify Downloads
import rasterio
from shapely.geometry import box

usableTIFFs = []
print(os.listdir(unprocessed_dir))
# Ensure the shapefile matches the TIF CRS
for tif_file in os.listdir(unprocessed_dir):
    if tif_file.endswith(".TIF") or tif_file.endswith(".tif"):
        tif_path = unprocessed_dir + '/' + tif_file
        with rasterio.open(tif_path) as src:
            # Reproject shapefile to match TIF file CRS
            aoi_geodf_proj = aoi_geodf.to_crs(src.crs)
            tif_bounds = box(*src.bounds)
            
            # Check containment
            for idx, geom in enumerate(aoi_geodf_proj.geometry):
                if tif_bounds.contains(geom):
                    usableTIFFs.append(tif_file)
                    print(f"Polygon {city} is fully inside {tif_file}")
                else:
                    print(f"Polygon {city} is NOT fully inside {tif_file}")
print(usableTIFFs)

['LC08_L2SP_039035_20150113_20200910_02_T1_MTL.txt', 'LC08_L2SP_039035_20150113_20200910_02_T1_SR_B2.TIF', 'LC08_L2SP_039035_20150113_20200910_02_T1_SR_B3.TIF', 'LC08_L2SP_039035_20150113_20200910_02_T1_SR_B4.TIF', 'LC08_L2SP_039035_20150113_20200910_02_T1_SR_B5.TIF', 'LC08_L2SP_039035_20150113_20200910_02_T1_SR_B6.TIF', 'LC08_L2SP_039035_20150113_20200910_02_T1_ST_B10.TIF', 'LC08_L2SP_039035_20150214_20200910_02_T1_MTL.txt', 'LC08_L2SP_039035_20150214_20200910_02_T1_SR_B2.TIF', 'LC08_L2SP_039035_20150214_20200910_02_T1_SR_B3.TIF', 'LC08_L2SP_039035_20150214_20200910_02_T1_SR_B4.TIF', 'LC08_L2SP_039035_20150214_20200910_02_T1_SR_B5.TIF', 'LC08_L2SP_039035_20150214_20200910_02_T1_SR_B6.TIF', 'LC08_L2SP_039035_20150214_20200910_02_T1_ST_B10.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_MTL.txt', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B2.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B3.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B4.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B5.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B6.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_ST_B10.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_MTL.txt', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B2.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B3.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B4.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B5.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B6.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_ST_B10.TIF']
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150113_20200910_02_T1_SR_B2.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150113_20200910_02_T1_SR_B3.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150113_20200910_02_T1_SR_B4.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150113_20200910_02_T1_SR_B5.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150113_20200910_02_T1_SR_B6.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150113_20200910_02_T1_ST_B10.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150214_20200910_02_T1_SR_B2.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150214_20200910_02_T1_SR_B3.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150214_20200910_02_T1_SR_B4.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150214_20200910_02_T1_SR_B5.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150214_20200910_02_T1_SR_B6.TIF
Polygon Pahrump_NV is NOT fully inside LC08_L2SP_039035_20150214_20200910_02_T1_ST_B10.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150205_20200909_02_T1_SR_B2.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150205_20200909_02_T1_SR_B3.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150205_20200909_02_T1_SR_B4.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150205_20200909_02_T1_SR_B5.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150205_20200909_02_T1_SR_B6.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150205_20200909_02_T1_ST_B10.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150221_20200909_02_T1_SR_B2.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150221_20200909_02_T1_SR_B3.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150221_20200909_02_T1_SR_B4.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150221_20200909_02_T1_SR_B5.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150221_20200909_02_T1_SR_B6.TIF
Polygon Pahrump_NV is fully inside LC08_L2SP_040035_20150221_20200909_02_T1_ST_B10.TIF
['LC08_L2SP_040035_20150205_20200909_02_T1_SR_B2.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B3.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B4.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B5.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_SR_B6.TIF', 'LC08_L2SP_040035_20150205_20200909_02_T1_ST_B10.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B2.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B3.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B4.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B5.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_SR_B6.TIF', 'LC08_L2SP_040035_20150221_20200909_02_T1_ST_B10.TIF']

In [ ]:
goodCoordinates = clipUnprocessedRasters(usableTIFFs, aoi_geodf_proj)

Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B2.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B3.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B4.TIF
Clipped, reprojected, and color-preserved TIF saved as ./Unprocessed/Clipped_LC08_L2SP_040035_20150205_20200909_02_T1_SR_B5.TIF

In [ ]:
for file in os.listdir(unprocessed_dir):
    if ".txt" in file or "Clipped_" in file:
        if '1arc_v3' in file:
            moveToRaw(file, 'DEM', f'{years[0]}-01-01', city)
            continue
        if 'LCMAP' in file:
            if 'LCPRI' in file:
                moveToRaw(file, 'Land_Cover', f'{years[0]}-01-01', city)
            continue
        date, band, coordinate = getMetaFromLandsatTIRs(file)
        if coordinate not in goodCoordinates:
            continue
        print(date, band)
        if band == 'B10':
            moveToRaw(file, 'LST', date, city)
        if band == 'B2':
            moveToRaw(file, 'Albedo', date, city)
        if band == 'B3':
            moveToRaw(file, 'NDWI', date, city)
        if band == 'B4':
            moveToRaw(file, 'Albedo', date, city)
            moveToRaw(file, 'NDVI', date, city)
        if band == 'B5':
            moveToRaw(file, 'Albedo', date, city)
            moveToRaw(file, 'NDVI', date, city)
            moveToRaw(file, 'NDWI', date, city)
        if band == 'B6':
            moveToRaw(file, 'Albedo', date, city)
        if band == 'MTL':
            moveToRaw(file, 'Albedo', date, city)
            moveToRaw(file, 'LST', date, city)
            moveToRaw(file, 'NDVI', date, city)
            moveToRaw(file, 'NDWI', date, city)

In [ ]:
clear_folder(unprocessed_dir)